#!/bin/bash

#init flags for options

#-o for output
#this flag will save in custom path our current directory
path=$PWD/file.txt
flag_o=false

specialChar='!@#$%^&*()_+[]{}|;:,.<>?'
uppercaseChar='A-Z'
lowrcaseChar='a-z'
numChar='0-9'
len=16

#handle parameters and options
set -- $(getopt -q no:sl: "$@")
for param in $@; do
	case $param in
	-n) numChar= ;; #no number char
	-o)
		if [[ -n "$2" && "$2" != -* ]]; then
			path="$2"
			shift 2
		else
			path=$PWD/file.txt
			shift
		fi
		flag_o=true
		;;                 #output
	-s) specialChar= ;; #no special char
	-l) len=$2 ;;       # len of password
	esac
	shift
done
len=${len//\'/}
path=${path//\'/}

#result depend on options
codingChar=$uppercaseChar$lowrcaseChar$numChar$specialChar

random_string=$(head /dev/urandom | tr -dc $codingChar | head -c $len)
if $flag_o; then
	echo "$random_string" >$path
	echo "Your password has been successfully saved in the default or given path"
else
	echo $random_string
fi
