#!/bin/bash

#Initialize variables for options
flag_s=false
flag_n=false
value_p=$(pwd)

#Parse option
while getopts ":"



  
#random_string=$(head /dev/uranJ:dom | tr -dc 'A-Za-z0-9!@#$%^&*()_+[]{}|;:,.<>?' | head -c 16)
