#!/bin/bash

#init flags for options

#-o for output
#this flag will save in custom path our current directory
flag_o=$PWD
#-s for not special char
flag_s=false
#-n for not numbers
flag_n=false
#-c for number of chars
flag_c=false

specialChar='!@#$%^&*()_+[]{}|;:,.<>?'
uppercaseChar='A-Z'
lowrcaseChar='a-z'
numChar='0-9'
len=16

#handle parameters and options
set -- $(getopt -q no:sc "$@")
for param in $@; do
	case $param in
	-n) flag_n=true ;;
	-o) flag_o=$2 ;;
	-s) flag_s=true ;;
	-c) flag_c=true ;;
	esac
	shift
done

if $flag_s; then
	specialChar=
fi
if $flag_n; then
	numChar=
fi

#result depend on options
codingChar=$uppercaseChar$lowrcaseChar$numChar$specialChar

random_string=$(head /dev/urandom | tr -dc $codingChar | head -c $len)

echo $random_string
